const galaxy = [
    { id: 0, name: "Sol", x: 480, y: 510, pois: [{ name: "Earth Agri-Hub", specialty: "grain", type: "Agricultural", description: "The crown jewel of the Sol system. Massive orbital biodomes provide grain for the entire sector." }, { name: "Mars Foundry", specialty: "iron", type: "Industrial", description: "Red dust covers every surface of this ancient, sprawling smelting complex." }, { name: "Io Base", specialty: "copper", type: "Industrial", description: "Just a wee colony to test the POI" }] },
    { id: 1, name: "Proxima Centauri", x: 519, y: 482, pois: [{ name: "Alpha Station", specialty: "copper", type: "Mining" }, { name: "Proxima Labs", specialty: "circuits", type: "Tech" }, { name: "TEST!", specialty: "iron", type: "Industrial", description: "Blah blah blah" }] },
    { id: 2, name: "Sirius", x: 580, y: 550, pois: [{ name: "Sirius Prime", specialty: "steel", type: "Industrial" }, { name: "Dog Star Energy", specialty: "cell", type: "Energy" }] },
    { id: 3, name: "Vega", x: 420, y: 410, pois: [{ name: "Vega Electronics", specialty: "circuits", type: "Tech" }, { name: "Lyra Harvesters", specialty: "synth", type: "Agricultural" }] },
    { id: 4, name: "Rigel", x: 650, y: 350, pois: [{ name: "Rigel Blue", specialty: "meds", type: "Medical" }, { name: "Orion Forges", specialty: "tools", type: "Industrial" }] },
    { id: 5, name: "Antares", x: 300, y: 600, pois: [{ name: "Scorpio Core", specialty: "cell", type: "Energy" }, { name: "Red Supergiant", specialty: "iron", type: "Mining" }] },
    { id: 6, name: "Altair", x: 480, y: 320, pois: [{ name: "Altair Fields", specialty: "grain", type: "Agricultural" }, { name: "Eagle Systems", specialty: "wire", type: "Tech" }] },
    { id: 7, name: "Deneb", x: 720, y: 500, pois: [{ name: "Cygnus Tools", specialty: "tools", type: "Industrial" }, { name: "Deneb Extractors", specialty: "copper", type: "Mining" }] },
    { id: 8, name: "Spica", x: 400, y: 700, pois: [{ name: "Virgo Pharmaceuticals", specialty: "meds", type: "Medical" }, { name: "Spica Agri", specialty: "grain", type: "Agricultural" }] },
    { id: 9, name: "Pollux", x: 600, y: 650, pois: [{ name: "Gemini Synth", specialty: "synth", type: "Agricultural" }, { name: "Pollux Steelworks", specialty: "steel", type: "Industrial" }] },
    { id: 10, name: "Arcturus", x: 250, y: 400, pois: [{ name: "Boötes Power", specialty: "cell", type: "Energy" }, { name: "Arcturus Heavy", specialty: "iron", type: "Mining" }] },
    { id: 11, name: "Castor", x: 620, y: 660, pois: [{ name: "Castor Tech", specialty: "wire", type: "Tech" }, { name: "Gemini Medical", specialty: "meds", type: "Medical" }] },
    { id: 12, name: "Regulus", x: 450, y: 800, pois: [{ name: "Leo Refineries", specialty: "copper", type: "Industrial" }, { name: "Regulus Chips", specialty: "circuits", type: "Tech" }] },
    { id: 13, name: "Polaris", x: 500, y: 200, pois: [{ name: "North Star Nav", specialty: "circuits", type: "Tech" }, { name: "Polaris Ice", specialty: "synth", type: "Agricultural" }] },
    { id: 14, name: "Mizar", x: 750, y: 750, pois: [{ name: "Ursa Major Energy", specialty: "cell", type: "Energy" }, { name: "Mizar Instruments", specialty: "tools", type: "Tech" }] },
    { id: 15, name: "Bellatrix", x: 680, y: 380, pois: [{ name: "Amazon Forges", specialty: "steel", type: "Industrial" }, { name: "Bellatrix Arms", specialty: "tools", type: "Tech" }] },
    { id: 16, name: "Betelgeuse", x: 700, y: 300, pois: [{ name: "Betelgeuse Miners", specialty: "iron", type: "Mining" }, { name: "Orion's Belt Station", specialty: "wire", type: "Tech" }] },
    { id: 17, name: "Aldebaran", x: 350, y: 350, pois: [{ name: "Taurus Agri", specialty: "grain", type: "Agricultural" }, { name: "Eye of the Bull", specialty: "cell", type: "Energy" }] },
    { id: 18, name: "Capella", x: 400, y: 250, pois: [{ name: "Auriga Biotech", specialty: "meds", type: "Medical" }, { name: "Capella Processors", specialty: "circuits", type: "Tech" }] },
    { id: 19, name: "Fomalhaut", x: 800, y: 400, pois: [{ name: "Piscis Austrinus", specialty: "synth", type: "Agricultural" }, { name: "Fomalhaut Ring", specialty: "copper", type: "Mining" }] },
    { id: 20, name: "Canopus", x: 550, y: 850, pois: [{ name: "Carina Shipyards", specialty: "steel", type: "Industrial" }, { name: "Canopus Arrays", specialty: "wire", type: "Tech" }] },
    { id: 21, name: "Achernar", x: 850, y: 600, pois: [{ name: "Eridanus Water", specialty: "synth", type: "Agricultural" }, { name: "Achernar Flatteners", specialty: "tools", type: "Industrial" }] },
    { id: 22, name: "Hadar", x: 300, y: 500, pois: [{ name: "Centaurus B", specialty: "meds", type: "Medical" }, { name: "Hadar Power", specialty: "cell", type: "Energy" }] },
    { id: 23, name: "Acrux", x: 450, y: 900, pois: [{ name: "Crux Mining", specialty: "iron", type: "Mining" }, { name: "Southern Cross Station", specialty: "grain", type: "Agricultural" }] },
    { id: 24, name: "Gacrux", x: 470, y: 880, pois: [{ name: "Gacrux Biotech", specialty: "meds", type: "Medical" }, { name: "Ruby Station", specialty: "synth", type: "Agricultural" }] },
    { id: 25, name: "Mimosa", x: 420, y: 890, pois: [{ name: "Mimosa Chips", specialty: "circuits", type: "Tech" }, { name: "Crux Energy", specialty: "cell", type: "Energy" }] },
    { id: 26, name: "Alnitak", x: 670, y: 320, pois: [{ name: "Alnitak Foundries", specialty: "steel", type: "Industrial" }, { name: "Flame Nebula Mine", specialty: "copper", type: "Mining" }] },
    { id: 27, name: "Alnilam", x: 690, y: 330, pois: [{ name: "Alnilam Harvesters", specialty: "grain", type: "Agricultural" }, { name: "Belt Central", specialty: "wire", type: "Tech" }] },
    { id: 28, name: "Mintaka", x: 710, y: 340, pois: [{ name: "Mintaka Tools", specialty: "tools", type: "Industrial" }, { name: "Mintaka Meds", specialty: "meds", type: "Medical" }] },
    { id: 29, name: "Saiph", x: 660, y: 280, pois: [{ name: "Saiph Energy", specialty: "cell", type: "Energy" }, { name: "Orion Deep Mine", specialty: "iron", type: "Mining" }] },
    { id: 30, name: "Dubhe", x: 400, y: 150, pois: [{ name: "Bear Station", specialty: "synth", type: "Agricultural" }, { name: "Dubhe Micro", specialty: "circuits", type: "Tech" }] },
    { id: 31, name: "Merak", x: 420, y: 140, pois: [{ name: "Merak Steel", specialty: "steel", type: "Industrial" }, { name: "Ursa Extractors", specialty: "copper", type: "Mining" }] },
    { id: 32, name: "Phecda", x: 450, y: 170, pois: [{ name: "Phecda Med", specialty: "meds", type: "Medical" }, { name: "Bowl Station", specialty: "grain", type: "Agricultural" }] },
    { id: 33, name: "Megrez", x: 480, y: 190, pois: [{ name: "Megrez Hub", specialty: "wire", type: "Tech" }, { name: "Ursa Major Energy", specialty: "cell", type: "Energy" }] },
    { id: 34, name: "Alioth", x: 520, y: 160, pois: [{ name: "Alioth Agri", specialty: "synth", type: "Agricultural" }, { name: "Black Bear Mine", specialty: "iron", type: "Mining" }] },
    { id: 35, name: "Alkaid", x: 550, y: 130, pois: [{ name: "Alkaid Forges", specialty: "tools", type: "Industrial" }, { name: "Tail Station", specialty: "circuits", type: "Tech" }] },
    { id: 36, name: "Sadr", x: 740, y: 480, pois: [{ name: "Sadr Core", specialty: "cell", type: "Energy" }, { name: "Cygnus Cross", specialty: "wire", type: "Tech" }] },
    { id: 37, name: "Gienah", x: 760, y: 460, pois: [{ name: "Gienah Wings", specialty: "tools", type: "Tech" }, { name: "Swan Fields", specialty: "grain", type: "Agricultural" }] },
    { id: 38, name: "Ruchba", x: 700, y: 520, pois: [{ name: "Ruchba Extract", specialty: "copper", type: "Mining" }, { name: "Cygnus Meds", specialty: "meds", type: "Medical" }] },
    { id: 39, name: "Albireo", x: 680, y: 450, pois: [{ name: "Albireo Double", specialty: "synth", type: "Agricultural" }, { name: "Beak Station", specialty: "steel", type: "Industrial" }] },
    { id: 40, name: "Mirfak", x: 300, y: 200, pois: [{ name: "Perseus Arm", specialty: "iron", type: "Mining" }, { name: "Mirfak Power", specialty: "cell", type: "Energy" }] },
    { id: 41, name: "Algol", x: 280, y: 220, pois: [{ name: "Demon Star Meds", specialty: "meds", type: "Medical" }, { name: "Algol Tech", specialty: "circuits", type: "Tech" }] },
    { id: 42, name: "Alpheratz", x: 800, y: 200, pois: [{ name: "Andromeda Gate", specialty: "wire", type: "Tech" }, { name: "Alpheratz Hub", specialty: "tools", type: "Industrial" }] },
    { id: 43, name: "Mirach", x: 850, y: 150, pois: [{ name: "Mirach Ghost", specialty: "synth", type: "Agricultural" }, { name: "Girdle Station", specialty: "steel", type: "Industrial" }] },
    { id: 44, name: "Almach", x: 900, y: 100, pois: [{ name: "Almach Agri", specialty: "grain", type: "Agricultural" }, { name: "Andromeda Deep", specialty: "copper", type: "Mining" }] },
    { id: 45, name: "Hamal", x: 200, y: 300, pois: [{ name: "Aries Ram", specialty: "iron", type: "Mining" }, { name: "Hamal Energy", specialty: "cell", type: "Energy" }] },
    { id: 46, name: "Sheratan", x: 180, y: 320, pois: [{ name: "Sheratan Forge", specialty: "tools", type: "Industrial" }, { name: "Aries Circuitry", specialty: "circuits", type: "Tech" }] },
    { id: 47, name: "Mesarthim", x: 160, y: 340, pois: [{ name: "Mesarthim Bio", specialty: "meds", type: "Medical" }, { name: "Ram's Horn", specialty: "wire", type: "Tech" }] },
    { id: 48, name: "Elnath", x: 380, y: 300, pois: [{ name: "Elnath Horn", specialty: "steel", type: "Industrial" }, { name: "Taurus Fields", specialty: "synth", type: "Agricultural" }] },
    { id: 49, name: "Alcyone", x: 320, y: 380, pois: [{ name: "Pleiades Hub", specialty: "meds", type: "Medical" }, { name: "Seven Sisters Tech", specialty: "circuits", type: "Tech" }] },
    { id: 50, name: "Atlas", x: 437, y: 551, pois: [{ name: "Atlas Support", specialty: "tools", type: "Industrial" }, { name: "Titan Station", specialty: "cell", type: "Energy" }, { name: "New POI", specialty: "iron", type: "Industrial", description: "TEST!" }] },
    { id: 51, name: "Electra", x: 447, y: 485, pois: [{ name: "Electra Agri", specialty: "grain", type: "Agricultural" }, { name: "Pleiades Mining", specialty: "copper", type: "Mining" }] },
    { id: 52, name: "Maia", x: 538, y: 442, pois: [{ name: "Maia Synth", specialty: "synth", type: "Agricultural" }, { name: "Maia Nebula", specialty: "wire", type: "Tech" }] },
    { id: 53, name: "Merope", x: 487, y: 453, pois: [{ name: "Merope Core", specialty: "iron", type: "Mining" }, { name: "Merope Steel", specialty: "steel", type: "Industrial" }] },
    { id: 54, name: "Taygeta", x: 315, y: 375, pois: [{ name: "Taygeta Power", specialty: "cell", type: "Energy" }, { name: "Taygeta Labs", specialty: "meds", type: "Medical" }] },
    { id: 55, name: "Celaeno", x: 517, y: 549, pois: [{ name: "Celaeno Fab", specialty: "tools", type: "Tech" }, { name: "Dark Sister", specialty: "circuits", type: "Tech" }] },
    { id: 56, name: "Pleione", x: 305, y: 395, pois: [{ name: "Pleione Harvest", specialty: "grain", type: "Agricultural" }, { name: "Pleione Extract", specialty: "copper", type: "Mining" }] },
    { id: 57, name: "Procyon", x: 500, y: 600, pois: [{ name: "Little Dog Station", specialty: "steel", type: "Industrial" }, { name: "Procyon Systems", specialty: "wire", type: "Tech" }] },
    { id: 58, name: "Gomeisa", x: 480, y: 620, pois: [{ name: "Gomeisa Agri", specialty: "synth", type: "Agricultural" }, { name: "Canis Minor Hub", specialty: "circuits", type: "Tech" }] },
    { id: 59, name: "Alphard", x: 300, y: 700, pois: [{ name: "Hydra Heart", specialty: "cell", type: "Energy" }, { name: "Alphard Mines", specialty: "iron", type: "Mining" }] },
    { id: 60, name: "Denebola", x: 400, y: 850, pois: [{ name: "Lion's Tail", specialty: "meds", type: "Medical" }, { name: "Denebola Farm", specialty: "grain", type: "Agricultural" }] },
    { id: 61, name: "Zosma", x: 420, y: 830, pois: [{ name: "Zosma Tech", specialty: "tools", type: "Tech" }, { name: "Leo Back", specialty: "wire", type: "Tech" }] },
    { id: 62, name: "Vindemiatrix", x: 380, y: 680, pois: [{ name: "Grape Gatherer", specialty: "synth", type: "Agricultural" }, { name: "Vindemiatrix Ore", specialty: "copper", type: "Mining" }] },
    { id: 63, name: "Porrima", x: 360, y: 720, pois: [{ name: "Porrima Twin", specialty: "circuits", type: "Tech" }, { name: "Virgo Steel", specialty: "steel", type: "Industrial" }] },
    { id: 64, name: "Zubeneschamali", x: 200, y: 600, pois: [{ name: "North Claw", specialty: "tools", type: "Industrial" }, { name: "Libra Power", specialty: "cell", type: "Energy" }] },
    { id: 65, name: "Zubenelgenubi", x: 220, y: 580, pois: [{ name: "South Claw", specialty: "iron", type: "Mining" }, { name: "Libra Agri", specialty: "grain", type: "Agricultural" }] },
    { id: 66, name: "Graffias", x: 250, y: 550, pois: [{ name: "Scorpius Claws", specialty: "meds", type: "Medical" }, { name: "Graffias Synth", specialty: "synth", type: "Agricultural" }] },
    { id: 67, name: "Dschubba", x: 270, y: 570, pois: [{ name: "Dschubba Wire", specialty: "wire", type: "Tech" }, { name: "Scorpion Head", specialty: "copper", type: "Mining" }] },
    { id: 68, name: "Sargas", x: 320, y: 650, pois: [{ name: "Sargas Steel", specialty: "steel", type: "Industrial" }, { name: "Scorpio Tail", specialty: "tools", type: "Industrial" }] },
    { id: 69, name: "Shaula", x: 340, y: 670, pois: [{ name: "The Stinger", specialty: "cell", type: "Energy" }, { name: "Shaula Circuits", specialty: "circuits", type: "Tech" }] },
    { id: 70, name: "Kaus Australis", x: 100, y: 700, pois: [{ name: "Bow South", specialty: "grain", type: "Agricultural" }, { name: "Sagittarius Mine", specialty: "iron", type: "Mining" }] },
    { id: 71, name: "Kaus Media", x: 120, y: 680, pois: [{ name: "Bow Middle", specialty: "synth", type: "Agricultural" }, { name: "Sagittarius Meds", specialty: "meds", type: "Medical" }] },
    { id: 72, name: "Kaus Borealis", x: 140, y: 660, pois: [{ name: "Bow North", specialty: "copper", type: "Mining" }, { name: "Sagittarius Wire", specialty: "wire", type: "Tech" }] },
    { id: 73, name: "Nunki", x: 80, y: 720, pois: [{ name: "Nunki Sea", specialty: "cell", type: "Energy" }, { name: "Nunki Steel", specialty: "steel", type: "Industrial" }] },
    { id: 74, name: "Ascella", x: 60, y: 740, pois: [{ name: "Ascella Armpit", specialty: "tools", type: "Industrial" }, { name: "Ascella Chips", specialty: "circuits", type: "Tech" }] },
    { id: 75, name: "Albaldah", x: 40, y: 760, pois: [{ name: "Albaldah Hub", specialty: "grain", type: "Agricultural" }, { name: "Albaldah Iron", specialty: "iron", type: "Mining" }] },
    { id: 76, name: "Dabih", x: 50, y: 500, pois: [{ name: "Capricornus Head", specialty: "synth", type: "Agricultural" }, { name: "Dabih Power", specialty: "cell", type: "Energy" }] },
    { id: 77, name: "Algedi", x: 30, y: 480, pois: [{ name: "Algedi Goat", specialty: "meds", type: "Medical" }, { name: "Algedi Copper", specialty: "copper", type: "Mining" }] },
    { id: 78, name: "Nashira", x: 70, y: 520, pois: [{ name: "Nashira Lucky", specialty: "steel", type: "Industrial" }, { name: "Nashira Wire", specialty: "wire", type: "Tech" }] },
    { id: 79, name: "Deneb Algedi", x: 90, y: 540, pois: [{ name: "Goat Tail", specialty: "tools", type: "Tech" }, { name: "Deneb Algedi Circuits", specialty: "circuits", type: "Tech" }] },
    { id: 80, name: "Sadalmelik", x: 100, y: 300, pois: [{ name: "Aquarius King", specialty: "grain", type: "Agricultural" }, { name: "Water Bearer", specialty: "synth", type: "Agricultural" }] },
    { id: 81, name: "Sadalsuud", x: 80, y: 320, pois: [{ name: "Luck of Lucks", specialty: "meds", type: "Medical" }, { name: "Sadalsuud Iron", specialty: "iron", type: "Mining" }] },
    { id: 82, name: "Skat", x: 120, y: 280, pois: [{ name: "Skat Leg", specialty: "copper", type: "Mining" }, { name: "Skat Power", specialty: "cell", type: "Energy" }] },
    { id: 83, name: "Albali", x: 140, y: 260, pois: [{ name: "Albali Swallower", specialty: "steel", type: "Industrial" }, { name: "Albali Wire", specialty: "wire", type: "Tech" }] },
    { id: 84, name: "Enif", x: 300, y: 100, pois: [{ name: "Pegasus Nose", specialty: "tools", type: "Industrial" }, { name: "Enif Chips", specialty: "circuits", type: "Tech" }] },
    { id: 85, name: "Scheat", x: 350, y: 80, pois: [{ name: "Pegasus Leg", specialty: "grain", type: "Agricultural" }, { name: "Scheat Energy", specialty: "cell", type: "Energy" }] },
    { id: 86, name: "Markab", x: 320, y: 120, pois: [{ name: "Markab Saddle", specialty: "synth", type: "Agricultural" }, { name: "Markab Iron", specialty: "iron", type: "Mining" }] },
    { id: 87, name: "Algenib", x: 380, y: 60, pois: [{ name: "Pegasus Wing", specialty: "copper", type: "Mining" }, { name: "Algenib Meds", specialty: "meds", type: "Medical" }] },
    { id: 88, name: "Homam", x: 280, y: 140, pois: [{ name: "Homam Hero", specialty: "steel", type: "Industrial" }, { name: "Homam Wire", specialty: "wire", type: "Tech" }] },
    { id: 89, name: "Matar", x: 260, y: 160, pois: [{ name: "Matar Rain", specialty: "tools", type: "Tech" }, { name: "Matar Circuits", specialty: "circuits", type: "Tech" }] },
    { id: 90, name: "Rasalgethi", x: 800, y: 800, pois: [{ name: "Hercules Head", specialty: "cell", type: "Energy" }, { name: "Rasalgethi Iron", specialty: "iron", type: "Mining" }] },
    { id: 91, name: "Rutilicus", x: 820, y: 780, pois: [{ name: "Rutilicus Copper", specialty: "copper", type: "Mining" }, { name: "Hercules Arm", specialty: "grain", type: "Agricultural" }] },
    { id: 92, name: "Kornephoros", x: 840, y: 820, pois: [{ name: "Club Bearer", specialty: "steel", type: "Industrial" }, { name: "Kornephoros Synth", specialty: "synth", type: "Agricultural" }] },
    { id: 93, name: "Sarin", x: 860, y: 760, pois: [{ name: "Sarin Meds", specialty: "meds", type: "Medical" }, { name: "Hercules Bow", specialty: "wire", type: "Tech" }] },
    { id: 94, name: "Marfik", x: 880, y: 840, pois: [{ name: "Marfik Elbow", specialty: "tools", type: "Industrial" }, { name: "Marfik Chips", specialty: "circuits", type: "Tech" }] },
    { id: 95, name: "Rasalhague", x: 900, y: 700, pois: [{ name: "Ophiuchus Head", specialty: "grain", type: "Agricultural" }, { name: "Rasalhague Power", specialty: "cell", type: "Energy" }] },
    { id: 96, name: "Cebalrai", x: 920, y: 680, pois: [{ name: "Dog of the Shepherd", specialty: "synth", type: "Agricultural" }, { name: "Cebalrai Iron", specialty: "iron", type: "Mining" }] },
    { id: 97, name: "Yed Prior", x: 940, y: 720, pois: [{ name: "Hand Before", specialty: "copper", type: "Mining" }, { name: "Yed Prior Meds", specialty: "meds", type: "Medical" }] },
    { id: 98, name: "Yed Posterior", x: 960, y: 660, pois: [{ name: "Hand Behind", specialty: "steel", type: "Industrial" }, { name: "Yed Posterior Wire", specialty: "wire", type: "Tech" }] },
    { id: 99, name: "Sabik", x: 980, y: 740, pois: [{ name: "Sabik Driver", specialty: "tools", type: "Tech" }, { name: "Sabik Circuits", specialty: "circuits", type: "Tech" }] }
];
